const dotenv = require("dotenv");
const mongoose = require("mongoose");
const ParkingSpot = require("../models/ParkingSpot");

dotenv.config();

const sampleParkingSpots = [
  {
    spotCode: "D1",
    lotName: "Central Lot",
    type: "disability",
    isAvailable: true,
    pricePerHour: 7,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3832, 43.6532] },
    totalSpaces: 1,
    description: "Accessible parking close to elevator",
  },
  {
    spotCode: "R1",
    lotName: "Central Lot",
    type: "regular",
    isAvailable: true,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3835, 43.6534] },
    totalSpaces: 1,
    description: "Regular spot near main entrance",
  },
  {
    spotCode: "EV1",
    lotName: "Central Lot",
    type: "EV",
    isAvailable: true,
    pricePerHour: 8,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3838, 43.6536] },
    totalSpaces: 1,
    description: "EV charging level 2",
  },
  {
    spotCode: "D2",
    lotName: "City Hall Garage",
    type: "disability",
    isAvailable: true,
    pricePerHour: 5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3854, 43.6518] },
    totalSpaces: 1,
    description: "Wheelchair accessible path nearby",
  },
  {
    spotCode: "R2",
    lotName: "City Hall Garage",
    type: "regular",
    isAvailable: false,
    pricePerHour: 5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3858, 43.6519] },
    totalSpaces: 1,
    description: "Covered regular spot",
  },
  {
    spotCode: "EV2",
    lotName: "City Hall Garage",
    type: "EV",
    isAvailable: true,
    pricePerHour: 7,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3862, 43.6521] },
    totalSpaces: 1,
    description: "Fast charging port",
  },
  {
    spotCode: "D3",
    lotName: "Union Station Lot",
    type: "disability",
    isAvailable: true,
    pricePerHour: 9,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3785, 43.6458] },
    totalSpaces: 1,
    description: "Near station accessible ramp",
  },
  {
    spotCode: "R3",
    lotName: "Union Station Lot",
    type: "regular",
    isAvailable: true,
    pricePerHour: 9,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3789, 43.646] },
    totalSpaces: 1,
    description: "High-demand downtown spot",
  },
  {
    spotCode: "EV3",
    lotName: "Union Station Lot",
    type: "EV",
    isAvailable: false,
    pricePerHour: 10,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3793, 43.6462] },
    totalSpaces: 1,
    description: "Charging currently occupied",
  },
  {
    spotCode: "D4",
    lotName: "Harbourfront Parking",
    type: "disability",
    isAvailable: true,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3808, 43.6395] },
    totalSpaces: 1,
    description: "Accessible waterfront access",
  },
  {
    spotCode: "R4",
    lotName: "Harbourfront Parking",
    type: "regular",
    isAvailable: true,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3811, 43.6398] },
    totalSpaces: 1,
    description: "Regular spot with easy exit",
  },
  {
    spotCode: "EV4",
    lotName: "Harbourfront Parking",
    type: "EV",
    isAvailable: true,
    pricePerHour: 7,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3815, 43.6401] },
    totalSpaces: 1,
    description: "EV charging near bay",
  },
  {
    spotCode: "D5",
    lotName: "Eaton Center Deck",
    type: "disability",
    isAvailable: false,
    pricePerHour: 8,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.379, 43.6552] },
    totalSpaces: 1,
    description: "Mall access disabled parking",
  },
  {
    spotCode: "R5",
    lotName: "Eaton Center Deck",
    type: "regular",
    isAvailable: true,
    pricePerHour: 8,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3794, 43.6554] },
    totalSpaces: 1,
    description: "Regular deck parking",
  },
  {
    spotCode: "EV5",
    lotName: "Eaton Center Deck",
    type: "EV",
    isAvailable: true,
    pricePerHour: 9,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3797, 43.6556] },
    totalSpaces: 1,
    description: "EV station on level 2",
  },
  {
    spotCode: "D6",
    lotName: "North York Hub",
    type: "disability",
    isAvailable: true,
    pricePerHour: 4,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.412, 43.7615] },
    totalSpaces: 1,
    description: "Free accessible public spot",
  },
  {
    spotCode: "R6",
    lotName: "North York Hub",
    type: "regular",
    isAvailable: true,
    pricePerHour: 4,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.4124, 43.7617] },
    totalSpaces: 1,
    description: "Regular commuter parking",
  },
  {
    spotCode: "EV6",
    lotName: "North York Hub",
    type: "EV",
    isAvailable: false,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.4128, 43.7619] },
    totalSpaces: 1,
    description: "EV spot occupied",
  },
  {
    spotCode: "R7",
    lotName: "Midtown Plaza",
    type: "regular",
    isAvailable: true,
    pricePerHour: 5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3999, 43.7082] },
    totalSpaces: 1,
    description: "Midtown plaza parking",
  },
  {
    spotCode: "EV7",
    lotName: "Midtown Plaza",
    type: "EV",
    isAvailable: true,
    pricePerHour: 7,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.4002, 43.7084] },
    totalSpaces: 1,
    description: "EV charger near entrance",
  },
  {
    spotCode: "V1",
    lotName: "Main Lot",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 4.5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.3833, 43.6533] },
    totalSpaces: 1,
    description: "Visitor parking near entrance",
  },
  {
    spotCode: "SQ1-D1",
    lotName: "Square One Mall",
    type: "disability",
    isAvailable: true,
    pricePerHour: 5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6464, 43.5931] },
    totalSpaces: 1,
    description: "Accessible parking near Entrance 3",
  },
  {
    spotCode: "SQ1-R1",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 4.5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6459, 43.5929] },
    totalSpaces: 1,
    description: "Regular parking near Walmart side",
  },
  {
    spotCode: "SQ1-R2",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: false,
    pricePerHour: 4.5,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6469, 43.5934] },
    totalSpaces: 1,
    description: "Busy regular spot by food district",
  },
  {
    spotCode: "SQ1-EV1",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: true,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6454, 43.5926] },
    totalSpaces: 1,
    description: "EV charging in P2 level",
  },
  {
    spotCode: "SQ1-EV2",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: true,
    pricePerHour: 6,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6461, 43.5937] },
    totalSpaces: 1,
    description: "EV charger near Cineplex entrance",
  },
  {
    spotCode: "SQ1-V1",
    lotName: "Square One Mall",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 4,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6467, 43.5925] },
    totalSpaces: 1,
    description: "Short-stay visitor parking",
  },
  {
    spotCode: "SQ1-V2",
    lotName: "Square One Mall",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 4,
    isPaid: true,
    location: { type: "Point", coordinates: [-79.6457, 43.5933] },
    totalSpaces: 1,
    description: "Visitor parking near west valet zone",
  },
  {
    spotCode: "SQ1-FR1",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6463, 43.5928] },
    totalSpaces: 1,
    description: "Free regular parking near Holt Renfrew entrance",
  },
  {
    spotCode: "SQ1-FR2",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6460, 43.5930] },
    totalSpaces: 1,
    description: "Free regular parking in north outdoor lot",
  },
  {
    spotCode: "SQ1-FR3",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6456, 43.5932] },
    totalSpaces: 1,
    description: "Free regular parking by community side",
  },
  {
    spotCode: "SQ1-FV1",
    lotName: "Square One Mall",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6468, 43.5930] },
    totalSpaces: 1,
    description: "Free visitor parking near transit terminal",
  },
  {
    spotCode: "SQ1-FV2",
    lotName: "Square One Mall",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6465, 43.5935] },
    totalSpaces: 1,
    description: "Free visitor parking near west lot",
  },
  {
    spotCode: "SQ1-FD1",
    lotName: "Square One Mall",
    type: "disability",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6458, 43.5927] },
    totalSpaces: 1,
    description: "Free accessible parking at Entrance 1",
  },
  {
    spotCode: "SQ1-FEV1",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6453, 43.5931] },
    totalSpaces: 1,
    description: "Free EV parking near P1 charging lane",
  },
  {
    spotCode: "SQ1-FEV2",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: false,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6451, 43.5929] },
    totalSpaces: 1,
    description: "Free EV parking currently occupied",
  },
  {
    spotCode: "SQ1-FR4",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6462, 43.5936] },
    totalSpaces: 1,
    description: "Free regular parking near east upper lot",
  },
  {
    spotCode: "SQ1-FR5",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6455, 43.5924] },
    totalSpaces: 1,
    description: "Free regular parking near parking deck ramp",
  },
  {
    spotCode: "SQ1-FR6",
    lotName: "Square One Mall",
    type: "regular",
    isAvailable: false,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6469, 43.5927] },
    totalSpaces: 1,
    description: "Free regular parking currently occupied",
  },
  {
    spotCode: "SQ1-FV3",
    lotName: "Square One Mall",
    type: "visitor",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6464, 43.5938] },
    totalSpaces: 1,
    description: "Free visitor parking close to main bus terminal",
  },
  {
    spotCode: "SQ1-FD2",
    lotName: "Square One Mall",
    type: "disability",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6459, 43.5923] },
    totalSpaces: 1,
    description: "Free accessible parking near entrance 5",
  },
  {
    spotCode: "SQ1-FEV3",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6452, 43.5934] },
    totalSpaces: 1,
    description: "Free EV parking near P2 charging lane",
  },
  {
    spotCode: "SQ1-FEV4",
    lotName: "Square One Mall",
    type: "EV",
    isAvailable: true,
    pricePerHour: 0,
    isPaid: false,
    location: { type: "Point", coordinates: [-79.6450, 43.5930] },
    totalSpaces: 1,
    description: "Free EV parking near south entrance",
  },
];

async function seedParkingSpots() {
  try {
    if (!process.env.MONGO_URI) {
      throw new Error("MONGO_URI is missing in backend/.env");
    }

    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    const operations = sampleParkingSpots.map((spot) => ({
      updateOne: {
        filter: { spotCode: spot.spotCode },
        update: { $set: spot },
        upsert: true,
      },
    }));

    const result = await ParkingSpot.bulkWrite(operations, { ordered: false });

    console.log("Seeding complete");
    console.log(`Inserted: ${result.upsertedCount || 0}`);
    console.log(`Updated: ${result.modifiedCount || 0}`);

    const total = await ParkingSpot.countDocuments();
    console.log(`Total Parking Spots in DB: ${total}`);
  } catch (error) {
    console.error("Seeding failed:", error.message);
    process.exitCode = 1;
  } finally {
    await mongoose.disconnect();
    console.log("Disconnected from MongoDB");
  }
}

seedParkingSpots();
